
<div>summer - 2010-11-12 09:34:20</div><div><a rel="nofollow" href="blog/comment-108.html">我一定会学架子鼓的。。。很帅很man很狂野，虽然差点被狂跳的fans挤死，但看到大家那种挥汗如雨也不顾一切疯狂的架势，还是觉得很有趣的。。。</a></div><br />

<div>summer - 2010-11-08 09:36:20</div><div><a rel="nofollow" href="blog/comment-107.html">看现场，很帅很激动。。。</a></div><br />

<div>philonis - 2010-10-28 18:47:58</div><div><a rel="nofollow" href="travel/comment-050.html">好长好长好长好长好长好长好长好长好长好长好长好长好长好长好长好长好长好长好长好长好长好长好长好长好长好长好长好长好长好长好长好长好长好长好长好长好长好长好长好长好长好长好长好长好长好长好长好长好长好长好长好长好长好长好长好长好长好长</a></div><br />

<div>lao  ma  - 2010-10-23 17:10:56</div><div><a rel="nofollow" href="blog/comment-106.html">这件衣服买的还不错,好看</a></div><br />

<div>pur - 2010-10-21 17:49:03</div><div><a rel="nofollow" href="blog/comment-106.html">　肯定是接待过您二位之后，Patagonia觉得太没面子了，于是就不卖鞋了……</a></div><br />

<div>yourtj - 2010-10-21 16:34:42</div><div><a rel="nofollow" href="blog/comment-106.html">话说08年我去这个店的时候 它还是卖鞋的 那天的折扣还巨高<br />
但是我和丁神没分清楚男鞋女鞋 买了两双女鞋回来 丁神还经常穿着这双女鞋呢<br />
哈哈</a></div><br />

<div>pur - 2010-10-21 13:14:05</div><div><a rel="nofollow" href="blog/comment-106.html">axe10同志，您在代购奶粉的时候，可以顺便带两件回来</a></div><br />

<div>summer - 2010-10-21 12:58:04</div><div><a rel="nofollow" href="blog/comment-106.html">很实在的试用报告，我表示同意。</a></div><br />

<div>axe10 - 2010-10-21 11:52:34</div><div><a rel="nofollow" href="blog/comment-106.html">介东西这么牛逼?淘宝代购400块。。</a></div><br />

<div>pur - 2010-10-18 11:05:07</div><div><a rel="nofollow" href="travel/comment-050.html">2D的相机咋能拍出3D效果？</a></div><br />

<div>ixchel - 2010-10-18 09:29:08</div><div><a rel="nofollow" href="travel/comment-050.html">给3D工牌上个图？</a></div><br />

<div>lao ma  - 2010-10-17 21:06:19</div><div><a rel="nofollow" href="travel/comment-050.html">看了游记长知识,我也知道什么是约旦河西岸和加沙地区了,今天以军还向加沙地区扔炮弹来呢</a></div><br />

<div>pur - 2010-10-17 20:02:41</div><div><a rel="nofollow" href="travel/comment-050.html">眼睛好尖啊~~<br />
以色列不停地在搞房地产，比如在约旦河西岸建犹太人定居点。</a></div><br />

<div>LAOMA - 2010-10-17 16:07:56</div><div><a rel="nofollow" href="travel/comment-050.html">耶路撒冷清真寺后边有塔吊,他们也在建房地产?</a></div><br />

<div>LIMA - 2010-10-16 21:56:57</div><div><a rel="nofollow" href="travel/comment-050.html">好可笑的叙述</a></div><br />

<div>summer - 2010-10-16 14:56:13</div><div><a rel="nofollow" href="travel/comment-050.html">好长的文字，好长的历史。。。</a></div><br />

<div>summer - 2010-09-27 09:11:40</div><div><a rel="nofollow" href="appraisal/comment-046.html">打压电影爱好者的典型人物。。。</a></div><br />

<div>pur - 2010-09-26 22:12:26</div><div><a rel="nofollow" href="blog/comment-105.html">这说明你仍然童心未泯，好事情啊</a></div><br />

<div>philonis - 2010-09-26 14:12:40</div><div><a rel="nofollow" href="blog/comment-105.html">我还以为那个龙猫是签证的一部分。。刚要赞叹一下。。</a></div><br />

<div>summer - 2010-09-19 22:09:53</div><div><a rel="nofollow" href="blog/comment-105.html">とても良い...</a></div><br />

<div>axe - 2010-09-13 16:07:49</div><div><a rel="nofollow" href="movie/comment-060.html">植入式广告~~</a></div><br />

<div>summer - 2010-09-10 17:28:01</div><div><a rel="nofollow" href="movie/comment-060.html">心灵世界最为深邃也最为恐怖。。。</a></div><br />

<div>summer - 2010-08-23 22:31:56</div><div><a rel="nofollow" href="blog/comment-104.html">那么，加油，震死我们吧。。。。</a></div><br />

<div>philonis - 2010-08-23 14:33:04</div><div><a rel="nofollow" href="blog/comment-104.html">您改行战地记者啦。。</a></div><br />

<div>summer - 2010-08-18 09:10:40</div><div><a rel="nofollow" href="blog/comment-103.html">耶路撒冷欢迎您。。。</a></div><br />

<div>philonis - 2010-08-11 17:56:28</div><div><a rel="nofollow" href="travel/comment-045.html">重读一遍，周末去一次。。</a></div><br />

<div>summer - 2010-08-11 09:08:25</div><div><a rel="nofollow" href="movie/comment-059.html">死后是否有生命，确实是一个值得推敲和研究的问题。不能解释的，往往称作迷信或魔幻，但我还是相信生命锁在灵魂里，找到钥匙便能开启，还是有一定道理的。女主角很个性，作为一个旅行记者和感性的女人被塑造得非常迷人。</a></div><br />

<div>感动中 - 2010-07-22 17:09:50</div><div><a rel="nofollow" href="blog/comment-101.html">相信他喜欢吃的是kfc</a></div><br />

<div>summer - 2010-07-20 21:09:24</div><div><a rel="nofollow" href="appraisal/comment-045.html">胡说，谁是美分党五毛党？。。。咱不屑于跟你们地球人玩。</a></div><br />

<div>philonis - 2010-07-20 14:57:17</div><div><a rel="nofollow" href="appraisal/comment-045.html">还有这个地方，过几天去看看</a></div><br />

<div>VC - 2010-07-20 09:59:37</div><div><a rel="nofollow" href="travel/comment-049.html">　看过一个西恩潘主演的，讲述Harvey Milk一生的电影，凭借此片，西恩潘得了2009年Oscar最佳男主角。推荐看一下。http://www.imdb.com/title/tt1013753/</a></div><br />

<div>pur - 2010-07-19 08:48:20</div><div><a rel="nofollow" href="blog/comment-101.html">如果碰到那个小喇嘛，买两个鸡腿给他吧，他最爱吃鸡腿了:)</a></div><br />

<div>新玉树,正在建立 - 2010-07-17 15:42:59</div><div><a rel="nofollow" href="blog/comment-101.html">遗憾的是,当卡这次我没有进去,路过时仰目端详着山腰那座寺院,默默祝福着他们.<br />
下个礼拜我还要去,有机会一定替你去问候他们.</a></div><br />

<div>summer - 2010-07-14 09:10:13</div><div><a rel="nofollow" href="blog/comment-102.html">最后一段真像一个销售代理:) 小小白就是好啊，羡煞我也，不像我的总是糊。。。</a></div><br />

<div>summer - 2010-07-05 12:57:39</div><div><a rel="nofollow" href="travel/comment-049.html">1、在这片土地上，“权利”“平等”，有得等喽。。。<br />
2、太有意思了，我在就好了。喜欢彩虹旗的样子。<br />
3、文风有那么一点“村上”的意思。。:)<br />
4、人物拍摄十分到位。</a></div><br />

<div>summer - 2010-06-28 22:10:15</div><div><a rel="nofollow" href="movie/comment-058.html">深有体会。。。不过，我希望有生之年能等到为国产动画流下我看《玩具3》《UP》时的眼泪。。。</a></div><br />

<div>pur - 2010-06-27 10:34:56</div><div><a rel="nofollow" href="blog/comment-101.html">那就先谢过了~<br />
有什么消息就给我留个言，或者发邮件也行，邮箱地址在每篇文章左下角都有。</a></div><br />

<div>你好 - 2010-06-26 22:14:26</div><div><a rel="nofollow" href="blog/comment-101.html">无意中看到你的博客,很不错的.<br />
玉树我会再去,有需要的事情,可以协助你处理<br />
你描述的当卡 承德小喇嘛我看出端倪了,希望下次我能去看他</a></div><br />

<div>summer - 2010-06-22 12:53:50</div><div><a rel="nofollow" href="blog/comment-101.html">不要郁闷，我们能做多少做多少。。。</a></div><br />


<div>summer - 2010-06-03 16:50:36</div><div><a rel="nofollow" href="movie/comment-057.html">我喜欢小眼睛男生，吼吼。。。也喜欢没牙仔和Dreamwork...</a></div><br />



<div>pur - 2010-06-02 11:04:11</div><div><a rel="nofollow" href="movie/comment-056.html">…… ……<br />

我虽然不觉得好看，但似乎也没这么难看。看来我还是容易满足的人！</a></div><br />



<div>buptfm - 2010-06-01 17:35:05</div><div><a rel="nofollow" href="movie/comment-056.html">本来一看完就想回来发帖子，初步构思为——跪求大家不要去影院看钢铁侠2。。之类的，后来觉得标题还不够震撼，一直没发。看的时候非常煎熬，也许是因为看的是国语配音版，男女主人公打嘴仗的片段简直叫人抓狂，滚动字幕出现的时候大家都松了一口气，有个小朋友非常友好地大声提醒大家：“还有一小段！”正匆匆经过他旁边准备离场的的一位大朋友也很友好地答复说：“我们知道的。”</a></div><br />



<div>summer - 2010-05-31 16:24:43</div><div><a rel="nofollow" href="movie/comment-056.html">看电影也要身经百战才能看到别人看不见的东西，比如躲在最后的小片尾。。。中国人性子太急，影片一结束拔腿就走，殊不知慢悠悠生活的西方人最喜欢把精彩结尾放在熬死人的滚动字幕之后。。。</a></div><br />



<div>pur - 2010-05-28 17:41:23</div><div><a rel="nofollow" href="travel/comment-024.html">　再没去过了，世界这么大，先去没去过的地方……<br />

不过担心同伴的问题，到了乌鲁木齐就能碰到一堆同路人。</a></div><br />



<div>dongxia_lu - 2010-05-27 18:41:59</div><div><a rel="nofollow" href="travel/comment-024.html">非常好的文章,谢谢!请问作者后来又去过新疆的其他地方吗?有无心得?我正在计划今年8月的新疆之行,有志同者,请帮忙牵线.谢谢.</a></div><br />



<div>summer - 2010-05-18 09:07:28</div><div><a rel="nofollow" href="movie/comment-055.html">很好的期待。。。</a></div><br />



<div>pur - 2010-05-14 09:36:08</div><div><a rel="nofollow" href="movie/comment-055.html">　要知道，Google的广告是会根据用户兴趣改变的~~所以只能说，你平时看的免费成人电影太多了……</a></div><br />



<div>tj - 2010-05-14 02:23:53</div><div><a rel="nofollow" href="movie/comment-055.html">哈哈 google 对这篇博文的广告<br />

<br />

免费成人电影<br />

The Amazing Graphics and Games All For You to Enjoy.<br />

webfetti.com<br />

<br />

BTW,你半年才看了3部电影啊 我大概都看了10部+了....<br />

<br />

</a></div><br />



<div>pur - 2010-04-28 07:36:00</div><div><a rel="nofollow" href="blog/comment-100.html">　不晓得啊，没有联系方式……</a></div><br />



<div>2010-04-23 22:53:18 - 2010-04-27 16:35:12</div><div><a rel="nofollow" href="blog/comment-100.html">想知道玉树的那个被父亲送去寺庙的小喇嘛平安吗？</a></div><br />



<div>2010-04-23 22:53:18 - 2010-04-27 16:35:10</div><div><a rel="nofollow" href="blog/comment-100.html">想知道玉树的那个被父亲送去寺庙的小喇嘛平安吗？</a></div><br />



<div>2010-04-23 22:53:18 - 2010-04-27 16:35:09</div><div><a rel="nofollow" href="blog/comment-100.html">想知道玉树的那个被父亲送去寺庙的小喇嘛平安吗？</a></div><br />



<div>1194425514 - 2010-04-23 22:53:18</div><div><a rel="nofollow" href="blog/comment-100.html">很高兴看到在这里看到玉树的原貌，祝福她的明天更好！</a></div><br />



<div>summer - 2010-04-20 10:30:03</div><div><a rel="nofollow" href="blog/comment-100.html">是的，一起去。。。</a></div><br />



<div>pur - 2010-04-06 18:30:39</div><div><a rel="nofollow" href="travel/comment-046.html">行家:)<br />

因为时间关系，没有走那条路，也没有去漠河，算是小小的缺憾吧。打算初夏的时候再去呼伦湖那边，看看高草野花的风景~</a></div><br />



<div>我没ID - 2010-04-05 23:33:12</div><div><a rel="nofollow" href="travel/comment-046.html">呵呵`你的游记有缺憾`没看到真正的草原景色、没感受到草原的民风`白来了！从阿尔山至伊敏至海拉尔、应该走的是两伊公路。建议你再走的时候，阿尔山-新巴尔虎左旗-新巴尔虎右旗-满洲里-陈巴尔虎旗-海拉尔。虽然绕了个圈子，但是收获一定会很多！</a></div><br />



<div>Philonis - 2010-03-22 21:52:49</div><div><a rel="nofollow" href="travel/comment-047.html">太长了。。。看到这里崩溃了，改日再看</a></div><br />



<div>pur - 2010-03-22 10:11:30</div><div><a rel="nofollow" href="travel/comment-047.html">其实，我真的，想看看，红衫军，是啥样子的，再拍点照片……遗憾啊！</a></div><br />



<div>axe - 2010-03-22 09:44:55</div><div><a rel="nofollow" href="travel/comment-047.html">泰国我就去了大皇宫 哭</a></div><br />



<div>buptfm - 2010-03-21 18:36:26</div><div><a rel="nofollow" href="travel/comment-047.html">你们跟红衫军是不是正好前后脚？运气真不错啊！</a></div><br />



<div>pur - 2010-03-17 17:55:02</div><div><a rel="nofollow" href="travel/comment-039.html">改过来了，多谢~</a></div><br />



<div>deng - 2010-03-17 16:22:56</div><div><a rel="nofollow" href="travel/comment-039.html">really nice blog abut SAN FRANCISCO, BTW it\'s marin county not city..</a></div><br />



<div>summer - 2010-03-16 18:09:00</div><div><a rel="nofollow" href="travel/comment-047.html">比你老婆写得好。。。</a></div><br />



<div>buptfm - 2010-03-05 17:41:21</div><div><a rel="nofollow" href="movie/comment-054.html">羡慕啊羡慕，你可能是我周围人里面唯一看了IMAX阿凡达的</a></div><br />



<div>pur - 2010-03-04 11:23:32</div><div><a rel="nofollow" href="movie/comment-054.html">华星每晚9~10点放新一天的票，您加完班可以去买，现在已经不排长队了，所以可以挑到很好的座位</a></div><br />



<div>Philonis - 2010-03-03 22:06:06</div><div><a rel="nofollow" href="movie/comment-054.html">我还挺着没看呢。。。</a></div><br />



<div>summer - 2010-03-03 11:57:19</div><div><a rel="nofollow" href="movie/comment-054.html">呵呵，愚昧和智慧并重的种族。<br />

阿凡达那双眼睛真迷人</a></div><br />



<div>summer - 2010-02-24 17:15:29</div><div><a rel="nofollow" href="movie/comment-053.html">唉，信仰是奢侈品的年代，电影也难逃宿命。用这剩下的半辈子好好折腾一下吧。。。</a></div><br />



<div>pur - 2010-02-02 22:01:21</div><div><a rel="nofollow" href="blog/comment-098.html">不败兄你好，别来无恙？</a></div><br />



<div>VC - 2010-02-02 19:58:46</div><div><a rel="nofollow" href="blog/comment-098.html">天下英雄出我辈，一入江湖岁月催。<br />

鸿图霸业谈笑间，不胜人生一场醉。<br />

提剑跨骑挥鬼雨，白骨如山鸟惊飞。<br />

尘世如潮人如水，只叹江湖几人回。</a></div><br />

